# buildspec.yml
version: 0.2

phases:
    install:
      runtime-versions:
        python: 3.8
      commands:
        - pip install -r requirements.txt

    build:
        commands:
            - make build
            - make deploy
            - make challenges
            - make invalidate

cache:
        paths:
            - '/root/.cache/pip/**/*'
