# buildspec.yml
version: 0.2

phases:
    install:
      runtime-versions:
        python: 3.8
        nodejs: 12
      commands:
        - pip install -r requirements.txt
        - npm install

    build:
        commands:
            - npm run build:all
            - bash ./bin/deploy.sh

cache:
        paths:
            - '/root/.cache/pip/**/*'
            - 'node_modules/**/*'
