base: https://epsalt.ca
title: E.P Salt
author: Evan Saltman
twitter: "@epsalt"
email: evan@epsalt.ca
description: Evan Saltman's personal website. Not related to epsom salts in any way.

content: content
site: site
templates: templates

markdown_extensions:
  - yafg

url:
  posts: "{{ page|date('%Y/%m') }}/{{ page|slug }}"

categories:
  tags: tag
